"""Small Browser session port implemented by automation backends."""

from typing import Protocol, runtime_checkable

from base_agent.browser.models import BrowserActionResult, BrowserSnapshot


@runtime_checkable
class BrowserSession(Protocol):
    async def navigate(self, url: str) -> BrowserActionResult: ...

    async def snapshot(self) -> BrowserSnapshot: ...

    async def click(self, selector: str) -> BrowserActionResult: ...

    async def fill(self, selector: str, text: str) -> BrowserActionResult: ...

    async def press(self, key: str) -> BrowserActionResult: ...

    async def select_option(self, selector: str, value: str) -> BrowserActionResult: ...

    async def screenshot(self, *, full_page: bool = False) -> bytes: ...
