"""Public package for the base-agent runtime."""

from base_agent.agent import Agent
from base_agent.models import (
    AgentResult,
    AgentResultStatus,
    EventType,
    Message,
    MessageRole,
    ModelRequest,
    ModelResponse,
    PendingInput,
    Run,
    RunStatus,
    RuntimeEvent,
    SkillReference,
    TokenUsage,
    ToolCall,
    ToolChoice,
    ToolDefinition,
    ToolResult,
    ToolResultStatus,
    WaitForInput,
)
from base_agent.profiles import AgentProfile
from base_agent.providers import ModelProvider, OpenAIChatProvider
from base_agent.run_handle import EventStreamingNotSupportedError, RunHandle
from base_agent.runtime import (
    AgentRuntime,
    ExecutionState,
    InvalidStateTransitionError,
    RuntimeCheckpoint,
    RuntimeContext,
)
from base_agent.skills import Skill, SkillLoader, SkillManifest, SkillRegistry
from base_agent.stores import (
    CheckpointStore,
    EventSink,
    EventStore,
    EventStream,
    InMemoryCheckpointStore,
    InMemoryEventStore,
    InMemoryRunStore,
    RunStore,
)
from base_agent.supervision import (
    BaseSupervisor,
    CompositeSupervisor,
    DuplicateToolCallDetector,
    ExecutionBudget,
    NoProgressDetector,
    SupervisionAction,
    SupervisionDecision,
    Supervisor,
)
from base_agent.tools import FunctionTool, Tool, ToolExecutor, ToolRegistry, tool

__version__ = "0.1.0"

__all__ = [
    "AgentResult",
    "AgentResultStatus",
    "Agent",
    "AgentProfile",
    "AgentRuntime",
    "BaseSupervisor",
    "CheckpointStore",
    "CompositeSupervisor",
    "DuplicateToolCallDetector",
    "ExecutionState",
    "ExecutionBudget",
    "EventSink",
    "EventStore",
    "EventStream",
    "EventType",
    "InvalidStateTransitionError",
    "EventStreamingNotSupportedError",
    "Message",
    "MessageRole",
    "ModelProvider",
    "OpenAIChatProvider",
    "ModelRequest",
    "ModelResponse",
    "PendingInput",
    "NoProgressDetector",
    "InMemoryCheckpointStore",
    "InMemoryEventStore",
    "InMemoryRunStore",
    "Run",
    "RunHandle",
    "RunStatus",
    "RunStore",
    "RuntimeCheckpoint",
    "RuntimeEvent",
    "Skill",
    "SkillLoader",
    "SkillManifest",
    "SkillReference",
    "SkillRegistry",
    "SupervisionAction",
    "SupervisionDecision",
    "Supervisor",
    "TokenUsage",
    "ToolCall",
    "ToolChoice",
    "ToolDefinition",
    "Tool",
    "ToolExecutor",
    "ToolRegistry",
    "ToolResult",
    "ToolResultStatus",
    "WaitForInput",
    "FunctionTool",
    "RuntimeContext",
    "tool",
    "__version__",
]
